### ISSUE TITLE
Change version number from 1.x.x to 1.0.0

### ISSUE THREAD

**Issue by nikohoffren** [nikohoffren/devgallery.io#3]
Change the version number in SECURITY.md from 1.x.x to 1.0.0

**Comment by Josepi161** [comment]
Hi, I just made the requested change.

Currently trying to get to grips with GitHubs processes, not 100% sure if i went about it correctly so please let me know if it appears i missed any steps or did anything unusual with regards to creating the pull request ect.

Thanks
